language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
before_install: rm Gemfile.lock || true
gemfile: Gemfile
script:
 - "bundle exec rake spec SPEC_OPTS='--format documentation --order random'"
env:
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
